version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/JustGoUp"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"

