name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  test-android:
    uses: ./.github/workflows/test-android.yml

  test-ios:
    uses: ./.github/workflows/test-ios.yml
