name: Release new version

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    uses: ./.github/workflows/android-build.yml
    with:
      project-dir: "JustGoUp/composeApp"
      version: ${{ github.ref_name }}
    secrets:
      ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

  create-release:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: JustGoUp-Android-${{ github.ref_name }}-Release
          path: ./apk

      - name: Create draft GitHub release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: JustGoUp ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: ./apk/justgoup-release-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
