name: Release new version

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    uses: ./.github/workflows/versioning.yml
          
  build-android:
    uses: ./.github/workflows/android-build.yml
    needs: version
    with:
      project-dir: "JustGoUp"
      version: ${{ needs.version.outputs.version }}

